### ISSUE TITLE
Push to Pypi?

### ISSUE THREAD

**Issue by dmr** [adamfeuer/rotate-backups#20]
There is another project with a confusingly similar name: https://pypi.python.org/pypi/rotate-backups/2.3.
But the github project has less Stars.

--> How do your feel about renaming this project, making it available on github and things?

There is not much with file rotation on PyPI: https://pypi.python.org/pypi?%3Aaction=search&term=rotate&submit=search

I can contribute a setup.py and a name suggestion: "rotatemybackup"

I don't want to be too philosophical here but we can also consider widening the scope of this project with a name like "rotatemyfile" for everything not only backups :)

**Comment by adamfeuer** [comment]
@dmr I didn't know about the other rotate-backups project. I'll consider changing the name - will let you know about that soon. I've been pretty busy and haven't been able to do much work on this project, but I should be able to give it some attention this coming weekend.

**Comment by dmr** [comment]
maybe "rotatemyfiles"?

**Comment by adamfeuer** [comment]
@dmr What about "simple-rotate-backups"? I want backups in the name, since that's the main use case at least for me and most people who use it.

**Comment by dmr** [comment]
Sounds like fighting "rotate-backups" but is ok for me. I just want to be able to install it via pypi

**Comment by adamfeuer** [comment]
Daniel,

Hi, have you seen this script?

https://github.com/maxharp3r/archive-rotator

It's another rotator that is actively maintained.

Regarding the name and PyPI - I took a look at my passion for this project
and my available time and I think I don't want to maintain this project any
more. So you're welcome to fork the project, rename it, and upload it to
PyPI!

I have a lot going on in my life and my attention can't be on this project
right now or likely in the next year or more. I would be happy to
contribute to your fork if I do have the need to make modifications to it.

How does that sound?

cheers
adam

**Comment by dmr** [comment]
Thanks für for hint to archive-rotator, I think I'll use that for my purpose :)
And good luck with your other projects!
