### ISSUE TITLE
ionice - busybox

### ISSUE THREAD

**Issue by eyJhb** [adamfeuer/rotate-backups#23]
When using `ionice` from `busybox` it does not accept the class names, but rather only the number.
Consider allowing specifying the number and name or rather only use the number to avoid confusing.

You can test this using Docker alpine

```
docker run --rm -it alpine sh
ionice -c idle
ionice -c 3
```
Thanks for the great backup script btw.!

**Comment by adamfeuer** [comment]
@eyJhb Is this a problem with `ionice` or the `rotate-backups` script?

**Comment by eyJhb** [comment]
@adamfeuer incompatibility with busyboxs ionice version of it. 
So a basic change that allows to specify numbers instead of names, would make this work in in minimal images such as alpine linux. :)

**Comment by adamfeuer** [comment]
@eyJhb ok, will you give me some steps to reproduce the problem then? I don't understand the steps you listed above.

**Comment by adamfeuer** [comment]
@eyJhb I am a docker and alpine user, by the way... but I just don't understand how you are setting the `rotate-backups` script nice with `ionice` using those steps.

Or are you asking to set the `rotate-backups` script priority to `idle`...? 

You're welcome to submit a Pull Request with a code fix and I'll help you get it merged.

**Comment by eyJhb** [comment]
If I set the params in my config for ionice idle , it will error out sine
it will try to call `ionice -c idle`, which isn't valid in Busyboxs version
of ionice, where it should be `ionice -c 3` instead.
But if you specify the number 3 in the rotate-backups config, it will
complain about invalid value (rotate-backups).

I will submit a PR tomorrow if I get the time ! Currently midnight here :)

Hope it cleared it up :)

**Comment by adamfeuer** [comment]
@eyJhb Thanks, that helps. Yes, PR would help - I'm looking forward to it!

**Comment by eyJhb** [comment]
This is rather embarrassing.. In my sleep deprived state, it opened this issue on the wrong project... It was meant for - https://github.com/xolox/python-rotate-backups :/ Makes much more sense, that I confused you :)

Sorry for the inconvenience ! I will just close this :)
